id: P010470
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W3CN8018
  title: སྙན་ངག་པ།
  author: ''
  volumes:
    70f60aa2dde84646bb4d48f90dd1414b:
      image_group_id: I3CN8020
      title: ''
      volume_number: 1
      total_pages: 72
      base_file: v001.txt
